services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./auth-service/db_up.sql:/docker-entrypoint-initdb.d/db_up.sql
      - db-data:/var/lib/postgresql/data
    restart: always

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "nikita@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16544:80"
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: nikita
      MINIO_ROOT_PASSWORD: helloworld111
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
  minio-storage:
