version: "3.8"

services:
  # Сервис для базы данных Postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./auth-service/db_up.sql:/docker-entrypoint-initdb.d/db_up.sql
      - db-data:/var/lib/postgresql/data
    restart: always

  # Сервис для pgAdmin
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "nikita@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16544:80"
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

  # Сервис для MinIO
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: nikita
      MINIO_ROOT_PASSWORD: helloworld111
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network
    restart: always

  # Сервис для RTSP-стримера
  rtsp-streamer:
    build:
      context: ./rtsp-streamer  # Указываем папку с проектом rtsp-streamer
      dockerfile: Dockerfile    # Путь к Dockerfile внутри папки rtsp-streamer
    env_file:
      - ./rtsp-streamer/.env   # Указываем путь к .env для rtsp-streamer
    ports:
      - "8554:8554"  # RTSP порт
    networks:
      - app-network
    depends_on:
      - minio
    restart: always

  # Сервис для Auth-сервиса
  auth-service:
    build:
      context: ./auth-service  # Указываем папку с проектом auth-service
      dockerfile: Dockerfile    # Путь к Dockerfile внутри папки auth-service
    env_file:
      - ./auth-service/.env   # Указываем путь к .env для auth-service
    ports:
      - "8000:8000"  # Порт для auth-service
    networks:
      - app-network
    depends_on:
      - postgres
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:
  minio-storage: